config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'
  resources :tweets
  resources :home
  resources :github

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 

  
  resources :users do
    resources :tweets
    resources :github
  end

  root to: "home#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	include ActiveModel::MassAssignmentSecurity

  belongs_to :user

  def self.add_tweets(user)
  	twitter = Twitter::REST::Client.new do |config|
		  config.consumer_key        = AppConfig['twitter']['consumer_key']
		  config.consumer_secret     = AppConfig['twitter']['consumer_secret']
		  config.access_token        = user.tw_token
		end
		tweets = twitter.user_timeline(user.username, {count: 10})
		tweets.each do |t|
			tweet = user.tweets.new
			tweet.username = t.user.screen_name
			tweet.text = t.text
			tweet.save
		end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def index
		@tweets = current_user.tweets
	end

  def new
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/index.html.erb
<% if @tweets.present? %>
	<div class="container">
	  <div class="row">
		<div class="span9 centred">
			<table class="table table-striped">
				<tr>
					<th>tweet</th>
				</tr>
			        <% @tweets.each do |f| %>
				<tr>
					<td><%= f.text %></td>
				</tr>
			<% end %>
			</table>
		</div>
	    <p><%= link_to "Printable Invoice (PDF)", user_tweets_path(@tweets, :format => 'pdf') %></p>
	   </div>
	</div>
	<% else %>
		<h3> No Tweets Found</h3>
<% end %>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>